@extends($current_layout)
@section('content')

<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">Salary Slip Detail</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="bx bx-home-alt"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ route('salary_slips.index') }}">Salary Slips</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ $slip->user->name }}</li>
            </ol>
        </nav>
    </div>
   
</div>

<div class="card radius-10">
    <div class="card-header d-flex justify-content-between align-items-center bg-transparent">
        <h5 class="mb-0">{{ $slip->user->name }} — {{ \Carbon\Carbon::parse($slip->month)->format('F Y') }}</h5>
        <div>
            @if($slip->status == 'pending')
                <a href="{{ route('salary_slips.edit', $slip->id) }}" class="btn btn-outline-secondary btn-sm">
                    <i class="bx bx-edit"></i> Edit
                </a>
                <button type="button" class="btn btn-success btn-sm" id="markPaidBtn" data-bs-toggle="modal" data-bs-target="#payModal">
                    <i class="bx bx-check-circle"></i> Mark as Paid
                </button>
            @endif
        </div>
    </div>
    <div class="card-body">
        @if($slip->status == 'pending')
        <div class="alert alert-info text-danger" role="alert">
            <i class="bx bx-info-circle"></i>
            <strong>Note:</strong> This salary slip is still <b>Pending</b>. Click "Mark as Paid" once payment has been made to record the transaction.
        </div>
    @else
        <div class="alert alert-success" role="alert">
            <i class="bx bx-check-circle"></i>
            <strong>Paid:</strong> This salary slip was paid on {{ $slip->payment_date->format('d-m-Y') }} by {{ $slip->paidBy->name ?? '-' }}.
        </div>
    @endif
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr><th style="width:250px;">Staff Name</th><td>{{ $slip->user->name }}</td></tr>
                <tr><th>Role</th><td>{{ ucfirst($slip->user->roles->first()->name ?? '-') }}</td></tr>
                <tr><th>Month</th><td>{{ \Carbon\Carbon::parse($slip->month)->format('F Y') }}</td></tr>
                <tr><th>Basic Salary</th><td>{{ number_format($slip->basic_salary, 2) }}</td></tr>
                <tr><th>Allowance</th><td>{{ number_format($slip->allowance, 2) }}</td></tr>
                <tr class="table-light"><th colspan="2">Attendance Summary</th></tr>
                <tr><th>Total Working Days</th><td>{{ $slip->total_days }}</td></tr>
                <tr><th>Present</th><td><span class="text-success">{{ $slip->present_days }}</span></td></tr>
                <tr><th>Absent</th><td><span class="text-danger">{{ $slip->absent_days }}</span></td></tr>
                <tr><th>Half Day</th><td><span class="text-info">{{ $slip->half_days }}</span></td></tr>
                <tr><th>Leave</th><td><span class="text-secondary">{{ $slip->leave_days }}</span></td></tr>
                <tr><th>Per Day Rate</th><td>{{ number_format($slip->per_day_rate, 2) }}</td></tr>
                <tr class="table-light"><th colspan="2">Deductions</th></tr>
                <tr><th>Attendance Deduction</th><td>{{ number_format($slip->attendance_deduction, 2) }}</td></tr>
                <tr><th>Manual Deduction</th><td>{{ number_format($slip->manual_deduction, 2) }}</td></tr>
                <tr><th>Advance Deduction</th><td>{{ number_format($slip->advance_deduction, 2) }}</td></tr>
                <tr><th>Total Deduction</th><td>{{ number_format($slip->deduction, 2) }}</td></tr>
                <tr class="table-success"><th>Net Salary</th><td><strong>{{ number_format($slip->net_salary, 2) }}</strong></td></tr>
                <tr>
                    <th>Status</th>
                    <td><span class="badge {{ $slip->status == 'paid' ? 'bg-success' : 'bg-warning' }}">{{ ucfirst($slip->status) }}</span></td>
                </tr>
                @if($slip->status == 'paid')
                    <tr><th>Payment Date</th><td>{{ $slip->payment_date->format('d-m-Y') }}</td></tr>
                    <tr><th>Paid By</th><td>{{ $slip->paidBy->name ?? '-' }}</td></tr>
                    <tr><th>Payment Method</th><td>{{ ucfirst($slip->transaction->payment_method ?? '-') }}</td></tr>
                    <tr><th>Reference No</th><td>{{ $slip->transaction->reference_no ?? '-' }}</td></tr>
                @endif
                <tr><th>Generated By</th><td>{{ $slip->generatedBy->name ?? '-' }}</td></tr>
            </table>
        </div>
    </div>
</div>

<!-- Mark as Paid Modal -->
<div class="modal fade" id="payModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('salary_slips.pay', $slip->id) }}" method="POST" id="payForm">
                @csrf
                <div class="modal-header bg-success">
                    <h5 class="modal-title">Mark as Paid</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Payment Method <span class="text-danger">*</span></label>
                        <select name="payment_method" class="form-select form-select-sm @error('payment_method') is-invalid @enderror" required>
    <option value="cash">Cash</option>
    <option value="bank_transfer">Bank Transfer</option>
    <option value="cheque">Cheque</option>
    <option value="easypaisa">Easypaisa</option>
    <option value="jazzcash">JazzCash</option>
</select>
                        @error('payment_method')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Reference No (optional)</label>
                        <input type="text" name="reference_no" class="form-control form-control-sm @error('reference_no') is-invalid @enderror">
                        @error('reference_no')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success btn-sm">Confirm Payment</button>
                    <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
$(document).ready(function () {

    @if(session('success'))
        toastr.success("{{ session('success') }}");
    @endif
    @if(session('error'))
        toastr.error("{{ session('error') }}");
    @endif
    @if($errors->any())
    toastr.error("{{ $errors->first() }}", 'Validation Error');
@endif

    $('#payForm').on('submit', function (e) {
        e.preventDefault();
        const form = this;

        Swal.fire({
            title: 'Confirm Payment?',
            text: "This will mark the salary as paid and record a transaction. This cannot be easily undone.",
            icon: 'question',
            showCancelButton: true,
            confirmButtonColor: '#28a745',
            cancelButtonColor: '#aaa',
            confirmButtonText: 'Yes, Confirm'
        }).then((result) => {
            if (result.isConfirmed) {
                form.submit();
            }
        });
    });
});
</script>
@endpush